One more fix

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -53,7 +53,7 @@ jobs:
         path: .coverage/
 
     - name: Line coverage quality gate
-      run: grep "> TOTAL.*LC=100%" .coverage/coverage.txt || echo "Line Code coverage quality gate failed" && grep "> TOTAL.*LC=100%" .coverage/coverage.txt && !
+      run: grep "> TOTAL.*LC=100%" .coverage/coverage.txt || echo "Line Code coverage quality gate failed" && grep "> TOTAL.*" .coverage/coverage.txt && !
 
     - name: MCDC coverage quality gate
-      run: grep "> TOTAL.*MCDC=100%" .coverage/coverage.txt || echo "MCDC Code coverage quality gate failed" && grep "> TOTAL.*LC=100%" .coverage/coverage.txt&& !
+      run: grep "> TOTAL.*MCDC=100%" .coverage/coverage.txt || echo "MCDC Code coverage quality gate failed" && grep "> TOTAL.*" .coverage/coverage.txt&& !
